Update JRuby to 9.1.17.0
This requires JRubyTest to be updated, as the return type of get() is now Long.

Note that the 9.2.x versions of JRuby have a more serious breakage:

[INFO] Running org.scijava.plugins.scripting.jruby.JRubyTest
NoMethodError: undefined method `getLanguageByName' for nil:NilClass
  <main> at hello.rb:3
[ERROR] null
org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `getLanguageByName' for nil:NilClass
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `getLanguageByName' for nil:NilClass
	at RUBY.<main>(hello.rb:3)
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.78 s <<< FAILURE! - in org.scijava.plugins.scripting.jruby.JRubyTest
[ERROR] testParameters(org.scijava.plugins.scripting.jruby.JRubyTest)  Time elapsed: 0.14 s  <<< FAILURE!
java.lang.AssertionError: expected:<Ruby> but was:<null>
	at org.scijava.plugins.scripting.jruby.JRubyTest.testParameters(JRubyTest.java:97)

[ERROR] testLocals(org.scijava.plugins.scripting.jruby.JRubyTest)  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.AssertionError: expected:<17> but was:<null>
	at org.scijava.plugins.scripting.jruby.JRubyTest.testLocals(JRubyTest.java:77)

Co-authored-by: Jan Eglinger <jan.eglinger@fmi.ch>